name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV
          echo "PATH=\$PATH:${{ github.workspace }}/src" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Debug src directory
        run: |
          python -c "import os; print(os.listdir('${{ github.workspace }}/src'))"

      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          pytest tests/labs/test_foo.py
        env:
          PYTHONPATH: ${{ github.workspace }}/src