name: CI/CD Pipeline

on:
  push:
    branches:
      - tech-red-qa-arch-refactor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el contenido del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.X
          architecture: 'x64'

      # Paso 3: Instalar las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Debug environment
      - name: Debug environment
        run: |
          echo "Shell type: $SHELL"
          echo "Bash version: $(bash --version)"
          echo "Python version: $(python --version)"

      # Paso 4: Configurar la variable de entorno PythonPath
      - name: Configure Python Path
        run: echo "PYTHONPATH=${{ github.workspace }}/tech_red_qa" >> $GITHUB_ENV

      # Paso 5: Instalar el proyecto
      - name: Install Project
        run: |
          python -m pip install -e .

      # Paso 6: Ejecutar las pruebas con Pytest
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/tech-red-qa/labs/tests
          pytest